package com.colegio.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "usuario")
public class Usuario {

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String usuarioId;
	@DynamoDBAttribute
	private String identificacion;
	@DynamoDBAttribute
	private String password;
	@DynamoDBAttribute
	private Iterable<Calificacion> calificaciones;
	
	public Usuario() {}
	
	public Usuario( String identificacion, String password, Iterable<Calificacion> calificaciones) {
		this.identificacion = identificacion;
		this.password = password;
		this.calificaciones = calificaciones;
	}
	
	public String getUsuarioId() {
		return usuarioId;
	}
	public void setUsuarioId(String usuarioId) {
		this.usuarioId = usuarioId;
	}
	public String getIdentificacion() {
		return identificacion;
	}
	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public Iterable<Calificacion> getCalificaciones() {
		return calificaciones;
	}
	public void setCalificaciones(Iterable<Calificacion> calificaciones) {
		this.calificaciones = calificaciones;
	}
	
	
}
